title:          tpkq
description:    my secret notes

baseurl:        ""
url:            http://itsuku.github.io

permalink:      none
markdown:       kramdown
author:
  name:         epkq
  url:          //example.com
  email:        have_not@had.com
